twingate-operator:
  # Twingate operator configurations
  #
  # **Required**: you have to specify `network` and
  #  - either `apiKey` or `existingAPIKeySecret`
  #  - either `remoteNetworkId`, `remoteNetworkName` or `existingRemoteNetworkIdSecret`
  #
  # **Restricting Operator to Specific Namespaces**
  # Use the `namespaces` property to restrict operator to monitor resources only in specific namespaces.
  # You can either:
  #  1. Specify a list of namespaces: ["foo-dev", "foo-stg"]
  #  2. Use globs to match multiple namespaces: ["*-dev", "*-stg"]
  #  3. Use negation to include all namespaces except those excluded: ["!kube-*"]
  #  4. Use multiple globs in one pattern: ["foo-*,!*-test"]
  #
  # Default value is an empty list (`[]`) which means operator will monitor or all namespaces.
  #
  # *Note:* Defining glob patterns as a separate array elements is different from defining
  # comma-separated patterns within a single element.
  # For example, `namespaces: ["foo-*", "!*-test"]` is not the same as `namespaces: ["foo-*,!*-test"]`
  # `namespaces: ["foo-*", "!*-test"]` will evaluate each glob pattern independently and combine the results.
  twingateOperator:
    network: ""
    apiKey: ""
    remoteNetworkId: "" # https://{network}.twingate.com/exit-networks/{remoteNetworkId}
    logFormat: "json"
    logVerbosity: "debug"
